In [4]:
a=10
b=20

In [5]:
print(a)
print(b)

10
20


In [6]:
print(type(a))

<class 'int'>


In [7]:
b=10.7
print(b)
print(type(b))

10.7
<class 'float'>


In [8]:
c="10.0"
print(c)
print(type(c))

10.0
<class 'str'>


In [9]:
d=True
print(d)
print(type(d))

True
<class 'bool'>


In [10]:
print(int(d))

1


In [11]:
l=[1,2,3,4]

In [12]:
print(l)

[1, 2, 3, 4]


In [13]:
print(type(l))
#list tuple set dict

<class 'list'>


#NUMPY

In [8]:
import numpy as np
l1=[1,2,3,4.0]
l2=[[1,2,3,],[4,5,6],[7,8,9]]

In [9]:
a1=np.array(l1)
print("L1:",l1)
print(type(l1))
print("Array 1:",a1,"\n",type(a1))

print(l1[0],type(l1[0]))
print(l1[-1],type(l1[-1]))
print(a1[0],type(a1[0]))

L1: [1, 2, 3, 4.0]
<class 'list'>
Array 1: [1. 2. 3. 4.] 
 <class 'numpy.ndarray'>
1 <class 'int'>
4.0 <class 'float'>
1.0 <class 'numpy.float64'>


In [10]:
a2=np.matrix(l2)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(a2.shape)
print(a2.sum())
print(np.linalg.det(a2))

(3, 3)
45
0.0


In [17]:
import pandas as pd
p1=pd.Series(l1,index=["a","b","c","d"])
print(p1)
print(type(p1))

a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64
<class 'pandas.core.series.Series'>


In [23]:
d1={"Name":["Jhon","Sam","Ram"],"Python Marks":[67,53,89],"Excel_Score":[76,59.9,23]}
df1=pd.DataFrame(d1)
print(df1)
print(type(df1))

   Name  Python Marks  Excel_Score
0  Jhon            67         76.0
1   Sam            53         59.9
2   Ram            89         23.0
<class 'pandas.core.frame.DataFrame'>


In [25]:
print(np.mean(df1['Python Marks']))

69.66666666666667


In [26]:
l3=[20,12,3]
print(np.mean(13))

13.0


In [27]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [29]:
import pandas as pd
df1=pd.read_csv("/content/drive/MyDrive/Dataset/Session 2/insurance.csv")

In [30]:
print(df1.shape)
print(df1.columns)

print(df1.info())


(1338, 7)
Index(['age', 'gender', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1335 non-null   float64
 1   gender    1317 non-null   object 
 2   bmi       1326 non-null   float64
 3   children  1275 non-null   float64
 4   smoker    774 non-null    object 
 5   region    1301 non-null   object 
 6   charges   1335 non-null   float64
dtypes: float64(4), object(3)
memory usage: 73.3+ KB
None


In [31]:
print(df1.head(4))

    age  gender     bmi  children smoker     region      charges
0  19.0  female  27.900       0.0    yes  southwest  16884.92400
1  18.0     NaN  33.770       1.0    NaN  southeast   1725.55230
2  28.0    male  33.000       3.0    NaN  southeast   4449.46200
3  33.0    male  22.705       0.0     no        NaN  21984.47061


In [32]:
print(df1.tail(4))

       age  gender    bmi  children smoker     region     charges
1334  18.0  female  31.92       0.0    NaN  northeast   2205.9808
1335  18.0  female  36.85       0.0    NaN  southeast   1629.8335
1336  21.0  female  25.80       0.0    NaN  southwest   2007.9450
1337  61.0  female  29.07       0.0    yes  northwest  29141.3603


In [34]:
print(df1.sample(10))

       age  gender     bmi  children smoker     region      charges
1081  32.0    male  27.835       1.0    NaN  northwest   4454.40265
262   52.0    male  24.320       3.0    yes  northeast  24869.83680
616   56.0  female  28.595       0.0     no  northeast  11658.11505
1224  41.0    male  23.940       1.0    NaN  northeast   6858.47960
171   49.0    male  30.300       0.0     no  southwest   8116.68000
777   45.0    male  39.805       0.0    NaN  northeast   7448.40395
510   56.0    male  32.110       1.0     no  northeast  11763.00090
396   43.0  female  34.400       3.0     no  southwest   8522.00300
197   45.0  female  28.600       2.0     no  southeast   8516.82900
224   42.0    male  24.640       0.0    yes  southeast  19515.54160
